"""renamed payment foreign key to user_tag

Revision ID: 06c6ec5dcf42
Revises: 24087c827771
Create Date: 2023-07-25 18:45:24.467123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c6ec5dcf42'
down_revision = '24087c827771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_tag', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_payment_tenant_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_payment_tenant_tag', 'users', ['user_tag'], ['user_tag'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_payment_tenant_tag', type_='foreignkey')
        batch_op.create_foreign_key('fk_payment_tenant_id', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_tag')

    # ### end Alembic commands ###
