"""removed total on FlatType

Revision ID: 0c8bcafd760d
Revises: 76f72a2fcf9c
Create Date: 2023-05-28 23:46:44.638231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8bcafd760d'
down_revision = '76f72a2fcf9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flattypes', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flattypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
