"""added blocks model

Revision ID: 0d3f57df0d80
Revises: 39d4437a75cd
Create Date: 2023-05-23 22:35:36.689654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3f57df0d80'
down_revision = '39d4437a75cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter', sa.CHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_flat_block', 'blocks', ['block_id'], ['id'])
        batch_op.drop_column('block')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('block', sa.CHAR(), nullable=True))
        batch_op.drop_constraint('fk_flat_block', type_='foreignkey')
        batch_op.drop_column('block_id')

    op.drop_table('blocks')
    # ### end Alembic commands ###
