"""ALL: added the username generation to init, added a few more fields to flat and nullable to multiple fields

Revision ID: 0ecb58358061
Revises: 
Create Date: 2023-08-17 17:55:08.204977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ecb58358061'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('block', sa.Integer(), nullable=False),
    sa.Column('for_rent', sa.BOOLEAN(), nullable=True),
    sa.Column('for_purchase', sa.BOOLEAN(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_freq', sa.Integer(), nullable=True),
    sa.Column('rent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=True),
    sa.Column('is_new', sa.BOOLEAN(), nullable=True),
    sa.Column('outstanding_rent', sa.Integer(), nullable=True),
    sa.Column('outstanding_service_charge', sa.Integer(), nullable=True),
    sa.Column('lease_duration', sa.Integer(), nullable=True),
    sa.Column('lease_start', sa.Date(), nullable=True),
    sa.Column('lease_expiry', sa.Date(), nullable=True),
    sa.Column('lease_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('flat_link',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('flat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('flat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], name='fk_payment_flat'),
    sa.ForeignKeyConstraint(['username'], ['users.username'], name='fk_payment_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('flat_link')
    op.drop_table('users')
    op.drop_table('flats')
    # ### end Alembic commands ###
