"""FLAT: changed for_purchase to for_sale

Revision ID: 1a0b7a3ee04d
Revises: c41a3725f0d7
Create Date: 2023-08-19 14:25:36.324335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1a0b7a3ee04d'
down_revision = 'c41a3725f0d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_sale', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('for_purchase')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('for_purchase', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('for_sale')

    # ### end Alembic commands ###
