"""got pissed and restarted DB

Revision ID: 23ea19b4c605
Revises: 
Create Date: 2023-08-03 19:48:04.829406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ea19b4c605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('block', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_tag', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('fisrt_name', sa.String(length=128), nullable=True),
    sa.Column('middle_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=True),
    sa.Column('is_new', sa.BOOLEAN(), nullable=True),
    sa.Column('outstanding_rent', sa.Integer(), nullable=True),
    sa.Column('outstanding_service_charge', sa.Integer(), nullable=True),
    sa.Column('lease_duration', sa.Integer(), nullable=True),
    sa.Column('lease_start', sa.DateTime(), nullable=True),
    sa.Column('lease_expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_tag')
    )
    op.create_table('flat_link',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('flat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flat_id'], ['flats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_tag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_tag'], ['users.user_tag'], name='fk_payment_tenant_tag'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('flat_link')
    op.drop_table('users')
    op.drop_table('flats')
    # ### end Alembic commands ###
