"""dropped all and rewrote foreign keys with name

Revision ID: 24087c827771
Revises: 6dfd328ca673
Create Date: 2023-07-25 18:39:46.491968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24087c827771'
down_revision = '6dfd328ca673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flattypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('rent', sa.Integer(), nullable=True),
    sa.Column('service_charge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_tag', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.Column('outstanding_rent', sa.Integer(), nullable=True),
    sa.Column('outstanding_service_charge', sa.Integer(), nullable=True),
    sa.Column('lease_duration', sa.Integer(), nullable=True),
    sa.Column('lease_start', sa.DateTime(), nullable=True),
    sa.Column('lease_expiry', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_user_role_id'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_tag')
    )
    op.create_table('flats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('block', sa.CHAR(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('flattype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flattype_id'], ['flattypes.id'], name='fk_flat_type_id'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_flat_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_payment_tenant_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('flats')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('flattypes')
    # ### end Alembic commands ###
