"""FLAT: moved all lease fields to lat model

Revision ID: 2b85db3c64a8
Revises: e442a3ddb271
Create Date: 2023-08-24 11:20:13.872044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b85db3c64a8'
down_revision = 'e442a3ddb271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('lease_expiry', sa.Date(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('outstanding_rent')
        batch_op.drop_column('outstanding_service_charge')
        batch_op.drop_column('lease_expiry')
        batch_op.drop_column('lease_start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_start', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('lease_expiry', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('outstanding_service_charge', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('outstanding_rent', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.drop_column('lease_expiry')
        batch_op.drop_column('lease_start')

    # ### end Alembic commands ###
