"""field name error correction

Revision ID: 591f3fe99c28
Revises: 23ea19b4c605
Create Date: 2023-08-03 21:01:00.932781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591f3fe99c28'
down_revision = '23ea19b4c605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=128), nullable=True))
        batch_op.drop_column('fisrt_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fisrt_name', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
