"""FLAT: removed payment_freq and added rent_overdue

Revision ID: 6be569644795
Revises: 2b85db3c64a8
Create Date: 2023-09-18 17:23:57.371158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6be569644795'
down_revision = '2b85db3c64a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rent_overdue', sa.Integer(), nullable=True))
        batch_op.drop_column('payment_freq')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_freq', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('rent_overdue')

    # ### end Alembic commands ###
