"""added relationship between tenant and flat

Revision ID: 6c72f1dbc8a6
Revises: 87c936e00b84
Create Date: 2023-07-21 20:45:31.432230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c72f1dbc8a6'
down_revision = '87c936e00b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_user_flat_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_flat', 'users', ['fk_user_flat_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_flat', type_='foreignkey')
        batch_op.drop_column('fk_user_flat_id')

    # ### end Alembic commands ###
