"""changed column name to status in Payment model

Revision ID: 6dfd328ca673
Revises: b9264d15f622
Create Date: 2023-07-24 21:55:12.831125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfd328ca673'
down_revision = 'b9264d15f622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=128), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
