"""is available bool field on FlatType

Revision ID: 6fd29d5e8f3a
Revises: b56f63ac9793
Create Date: 2023-05-29 23:51:25.676708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd29d5e8f3a'
down_revision = 'b56f63ac9793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flattypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flattypes', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
