"""USER & FLAT: swapped lease_duration from user to flat model

Revision ID: 71d75faba4d4
Revises: f2eb939024b1
Create Date: 2023-08-24 11:05:13.139717

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71d75faba4d4'
down_revision = 'f2eb939024b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_duration', sa.Date(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lease_duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_duration', mysql.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.drop_column('lease_duration')

    # ### end Alembic commands ###
