"""added total back to Flattypes

Revision ID: 7bda507b00ed
Revises: 0c8bcafd760d
Create Date: 2023-05-28 23:48:34.306775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bda507b00ed'
down_revision = '0c8bcafd760d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flattypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flattypes', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###
