"""initial migration

Revision ID: 87c936e00b84
Revises: 
Create Date: 2023-07-21 20:41:21.448084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c936e00b84'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flattypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('rent', sa.Integer(), nullable=True),
    sa.Column('service_charge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('flats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('block', sa.CHAR(), nullable=True),
    sa.Column('fk_flat_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_flat_type_id'], ['flattypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_tag', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('number', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_staff', sa.BOOLEAN(), nullable=True),
    sa.Column('joined_date', sa.DateTime(), nullable=True),
    sa.Column('outstanding_rent', sa.Integer(), nullable=True),
    sa.Column('outstanding_service_charge', sa.Integer(), nullable=True),
    sa.Column('lease_duration', sa.Integer(), nullable=True),
    sa.Column('lease_start', sa.DateTime(), nullable=True),
    sa.Column('lease_expiry', sa.DateTime(), nullable=True),
    sa.Column('fk_user_role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_user_role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_tag')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fk_payment_tenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fk_payment_tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('users')
    op.drop_table('flats')
    op.drop_table('roles')
    op.drop_table('flattypes')
    # ### end Alembic commands ###
