"""removed is_staff field from User model

Revision ID: b9264d15f622
Revises: 6c72f1dbc8a6
Create Date: 2023-07-23 21:45:58.515608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9264d15f622'
down_revision = '6c72f1dbc8a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_staff')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_staff', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
