"""FLAT: added buying cost field

Revision ID: c41a3725f0d7
Revises: 0ecb58358061
Create Date: 2023-08-19 13:48:14.889989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41a3725f0d7'
down_revision = '0ecb58358061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flats', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
