"""added name field to flats

Revision ID: e29c0e1334a8
Revises: 3e6b190d4c7a
Create Date: 2023-05-23 20:55:48.927991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29c0e1334a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('flats', schema=None) as batch_op:
    #     batch_op.add_column(sa.Column('type_name', sa.String(length=64), nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('flats', schema=None) as batch_op:
    #     batch_op.drop_column('type_name')
    pass
    # ### end Alembic commands ###
