"""USER: removed lease_amount field

Revision ID: f2eb939024b1
Revises: 1a0b7a3ee04d
Create Date: 2023-08-21 20:08:50.772572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2eb939024b1'
down_revision = '1a0b7a3ee04d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lease_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lease_amount', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
